### ISSUE TITLE
Missing Selenium Manager binary in package

### ISSUE THREAD

**Issue by vringar** [conda-forge/selenium-feedstock#63]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Starting with Selenium 4.11 the python package ships with the Selenium Manager binary [according to this blog post](https://www.selenium.dev/blog/2023/whats-new-in-selenium-manager-with-selenium-4.11.0/).

However, when trying to use Selenium 4.11.2 from conda-forge, I get the following error:
```
browser_manager      - ERROR    - BROWSER 3176617592: Crash in driver, restarting browser manager
Traceback (most recent call last):
  File "/run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 73, in driver_location
    args = [str(self.get_binary()), "--browser", browser]
                ^^^^^^^^^^^^^^^^^
  File "/run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/common/selenium_manager.py", line 57, in get_binary
    raise WebDriverException(f"Unable to obtain working Selenium Manager binary; {path}")
selenium.common.exceptions.WebDriverException: Message: Unable to obtain working Selenium Manager binary; /run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/run/media/stefan/02e400c2-1bdd-4d46-a0dd-044d6b4f3af4/Projekte/openwpm/OpenWPM/openwpm/browser_manager.py", line 716, in run
    driver, browser_profile_path, display = deploy_firefox.deploy_firefox(
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/stefan/02e400c2-1bdd-4d46-a0dd-044d6b4f3af4/Projekte/openwpm/OpenWPM/openwpm/deploy_browsers/deploy_firefox.py", line 141, in deploy_firefox
    driver = webdriver.Firefox(
             ^^^^^^^^^^^^^^^^^^
  File "/run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/firefox/webdriver.py", line 59, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/common/driver_finder.py", line 41, in get_path
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for firefox using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location
```

And when I check the path `/run/media/stefan/SourceCode/mambaforge/envs/openwpm/lib/python3.11/site-packages/selenium/webdriver/common/linux/selenium-manager`  the `linux` folder doesn't exist and the binary is not found.

I'm assuming this is a packaging issue, because the official release includes the binary.

### Installed packages

```shell
# packages in environment at /run/media/stefan/SourceCode/mambaforge/envs/openwpm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiobotocore               2.5.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.5           py311h459d7ec_0    conda-forge
aioitertools              0.11.0             pyhd8ed1ab_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.7.0                hf8751d9_2    conda-forge
aws-c-cal                 0.6.0                h93469e0_0    conda-forge
aws-c-common              0.8.23               hd590300_0    conda-forge
aws-c-compression         0.2.17               h862ab75_1    conda-forge
aws-c-event-stream        0.3.1                h9599702_1    conda-forge
aws-c-http                0.7.11               hbe98c3e_0    conda-forge
aws-c-io                  0.13.28              h3870b5a_0    conda-forge
aws-c-mqtt                0.8.14               h2e270ba_2    conda-forge
aws-c-s3                  0.3.13               heb0bb06_2    conda-forge
aws-c-sdkutils            0.1.11               h862ab75_1    conda-forge
aws-checksums             0.1.16               h862ab75_1    conda-forge
aws-crt-cpp               0.20.3               he9c0e7f_4    conda-forge
aws-sdk-cpp               1.10.57             hbc2ea52_17    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
black                     23.7.0          py311h38be061_1    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
botocore                  1.29.76            pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h409f033_3    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.6           unix_pyh707e725_0    conda-forge
codecov                   2.1.13             pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
coverage                  7.2.7           py311h459d7ec_0    conda-forge
cryptography              41.0.2          py311h63ff55d_0    conda-forge
dataclasses-json          0.5.14                   pypi_0    pypi
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
distlib                   0.3.7              pyhd8ed1ab_0    conda-forge
docutils                  0.20.1          py311h38be061_0    conda-forge
domain-utils              0.7.1                    pypi_0    pypi
easyprocess               1.1                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
frozenlist                1.4.0           py311h459d7ec_0    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gcsfs                     2023.6.0           pyhd8ed1ab_0    conda-forge
geckodriver               0.33.0               hd2f7af9_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
google-api-core           2.11.1             pyhd8ed1ab_0    conda-forge
google-auth               2.22.0             pyh1a96a4e_0    conda-forge
google-auth-oauthlib      1.0.0              pyhd8ed1ab_1    conda-forge
google-cloud-core         2.3.3              pyhd8ed1ab_0    conda-forge
google-cloud-storage      2.10.0             pyh1a96a4e_0    conda-forge
google-crc32c             1.1.2           py311h98db957_4    conda-forge
google-resumable-media    2.5.0              pyhd8ed1ab_0    conda-forge
googleapis-common-protos  1.60.0             pyhd8ed1ab_0    conda-forge
grpcio                    1.56.2          py311ha6695c7_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
identify                  2.5.26             pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ipython                   8.14.0             pyh41d4057_0    conda-forge
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
jedi                      0.19.0             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
jsonschema                4.18.6                   pypi_0    pypi
jsonschema-specifications 2023.7.1                 pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.1               h659d440_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
leveldb                   1.23                 h0b3b9e0_1    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libarrow                  12.0.1           h657c46f_7_cpu    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libgoogle-cloud           2.12.0               h840a212_1    conda-forge
libgrpc                   1.56.2               h3905398_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libnuma                   2.0.16               h0b41bf4_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libprotobuf               4.23.3               hd1fb520_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libthrift                 0.18.1               h8fd135c_2    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libuv                     1.44.2               hd590300_1    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markdown                  3.4.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py311h459d7ec_0    conda-forge
marshmallow               3.20.1                   pypi_0    pypi
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
multidict                 6.0.4           py311h2582759_0    conda-forge
multiprocess              0.70.15         py311h459d7ec_0    conda-forge
mypy                      1.4.1           py311h459d7ec_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
nodeenv                   1.8.0              pyhd8ed1ab_0    conda-forge
nodejs                    18.16.1              hf52ce11_0    conda-forge
numpy                     1.25.2          py311h64a7726_0    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
orc                       1.9.0                h385abfd_1    conda-forge
outcome                   1.2.0              pyhd8ed1ab_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.3           py311h320fe9a_1    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.11.2             pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    10.0.0          py311h0b84326_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
plyvel                    1.5.0                    pypi_0    pypi
pre-commit                3.3.3              pyha770c72_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
protobuf                  4.23.3          py311hbec7ed6_0    conda-forge
psutil                    5.9.5           py311h2582759_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   12.0.1          py311h39c9aba_7_cpu    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.4.0              pyhd8ed1ab_0    conda-forge
pytest-asyncio            0.21.1             pyhd8ed1ab_0    conda-forge
pytest-cov                4.1.0              pyhd8ed1ab_0    conda-forge
python                    3.11.4          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyvirtualdisplay          3.0             py311h38be061_3    conda-forge
pyyaml                    6.0             py311hd4cff14_5    conda-forge
rdma-core                 28.9                 h59595ed_1    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
redis-py                  4.6.0              pyhd8ed1ab_0    conda-forge
referencing               0.30.0                   pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-file             1.5.1                    pypi_0    pypi
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rpds-py                   0.9.2                    pypi_0    pypi
rsa                       4.9                pyhd8ed1ab_0    conda-forge
s2n                       1.3.46               h06160fa_0    conda-forge
s3fs                      2023.6.0           pyhd8ed1ab_0    conda-forge
selenium                  4.11.2             pyhd8ed1ab_0    conda-forge
sentry-sdk                1.29.2             pyhd8ed1ab_0    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    7.1.2              pyhd8ed1ab_0    conda-forge
sphinx-markdown-tables    0.0.17             pyh6c4a22f_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tldextract                2.2.2                    pypi_0    pypi
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
tranco                    0.6                      pypi_0    pypi
trio                      0.22.2          py311h38be061_0    conda-forge
trio-websocket            0.10.3             pyhd8ed1ab_0    conda-forge
types-pyopenssl           23.2.0.2                 pypi_0    pypi
types-pyyaml              6.0.12.11                pypi_0    pypi
types-redis               4.6.0.3                  pypi_0    pypi
types-tabulate            0.9.0.3                  pypi_0    pypi
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing-inspect            0.9.0                    pypi_0    pypi
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucx                       1.14.1               hf587318_2    conda-forge
ukkonen                   1.0.1           py311h4dd048b_3    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
virtualenv                20.24.2            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.0             pyhd8ed1ab_0    conda-forge
wrapt                     1.15.0          py311h2582759_0    conda-forge
wsproto                   1.2.0              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yarl                      1.9.2           py311h459d7ec_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

### Environment info

```shell
active environment : openwpm
    active env location : /run/media/stefan/SourceCode/mambaforge/envs/openwpm
            shell level : 1
       user config file : /home/stefan/.condarc
 populated config files : /run/media/stefan/SourceCode/mambaforge/.condarc
                          /home/stefan/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.8.final.0
       virtual packages : __linux=6.4.6=0
                          __glibc=2.37=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /run/media/stefan/SourceCode/mambaforge  (writable)
      conda av data dir : /run/media/stefan/SourceCode/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /run/media/stefan/SourceCode/mambaforge/pkgs
                          /home/stefan/.conda/pkgs
       envs directories : /run/media/stefan/SourceCode/mambaforge/envs
                          /home/stefan/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.8 Linux/6.4.6-1-MANJARO manjaro/23.0.0 glibc/2.37
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by bollwyvl** [comment]
Thanks for the report: I'll investigate getting a fix out (with a test), and/or marking the `_0` build broken.

**Comment by bollwyvl** [comment]
Ah... had a deeper look at the links and situation, it's a bit more complicated than "copy more files": 

> [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) is a binary tool (implemented in Rust) that provides automated driver management for Selenium. [Selenium Manager](https://www.selenium.dev/documentation/selenium_manager/) is still in beta, although it is becoming a relevant component of Selenium.

While it's cut from _some_ of the same upstream tags as conda-forge's currently-named `selenium` (just for python), this probably needs to be a separate, dedicated feedstock, e.g. `conda-forge/selenium-manager-feedstock`. 

Best case scenario, it will work with just `cargo install`, worst case will have to deal with `bazel`. 

At any rate: I _don't_ think the current releases of _this_ repo should be marked `broken` just yet. Once `selenium-manager` _is_ a thing, we can look at the best way to go.

**Comment by vringar** [comment]
Just FYI, this is my current workaround: https://github.com/openwpm/OpenWPM/blob/043ebadaeec4bc383c40abcdc1f99efbd7fe4a9d/openwpm/deploy_browsers/deploy_firefox.py#L140-L151

**Comment by bollwyvl** [comment]
Thanks for the work-around.

I've started looking into packaging `selenium-manager`: https://github.com/conda-forge/staged-recipes/pull/23634

This would deliver `selenium-manager(.exe)` to `$PREFIX/bin` or `%PREFIX%/Scripts`.

The package in _this_ repo is looking for a file in a specific place that will end up in `$PREFIX/lib/python-3.XX/site-packages/selenium/webdriver/common/{os}/selenium-manager(.exe)`, depending on where it gets installed. One approach for working around this will be to make wrapper scripts that forward the given arguments to the real executable on `$PATH`. Either way, it will take a bit to see how it shakes out.

**Comment by bollwyvl** [comment]
An alternative, of course, would be to patch the method that locates `selenium-manager(.exe)` with a light wrapper around `shutil.which`.
